### PR TITLE
alerting for peers stops after one alert

### LINKED ISSUE #812: Monitor: alerts never stop
**Additional information:**
 - OS: Linux
 - IPFS Cluster version: master
 - Installation method: source

**Describe the bug:**

When the new monitor, alerts are triggered constantly whenever a peer dissapears. This causes re-pinning attemps constantly. We should probably not alert all the time, as some peers may as well never come back again. Possible related to #410 

@lanzafame maybe there's a simple fix for this?

### PR DESCRIPTION
**Pull request by lanzafame**
Resolves #812.

This PR still requires clarification of whether the alerting for a peer should stop after one alert or several.

### CODE REVIEW

File: monitor/metrics/checker.go [hunk 1]
```diff
@@ -26,6 +27,9 @@ type Checker struct {
 	alertCh   chan *api.Alert
 	metrics   *Store
 	threshold float64
+
+	failedPeersMu sync.Mutex
+	failedPeers   map[peer.ID]bool
```
Comment (hsanjuan) [inline monitor/metrics/checker.go]: `map[peer.ID]struct{}` ?

File: monitor/metrics/checker.go [hunk 2]
```diff
@@ -89,6 +94,15 @@ func (mc *Checker) alertIfExpired(metric *api.Metric) error {
 }
 
 func (mc *Checker) alert(pid peer.ID, metricName string) error {
+	mc.failedPeersMu.Lock()
+	if mc.failedPeers[pid] {
+		mc.metrics.RemovePeer(pid)
+		delete(mc.failedPeers, pid)
+		return nil
```
Comment (hsanjuan) [inline monitor/metrics/checker.go]: returning without `Unlock()`.

File: monitor/metrics/store.go [hunk 3]
```diff
@@ -47,6 +47,15 @@ func (mtrs *Store) Add(m *api.Metric) {
 	window.Add(m)
 }
 
+// RemovePeer removes all metrics related to a peer from the Store.
+func (mtrs *Store) RemovePeer(pid peer.ID) {
+	mtrs.mux.Lock()
+	for _, mtrs := range mtrs.byName {
+		delete(mtrs, pid)
+	}
+	mtrs.mux.Unlock()
```
Comment (hsanjuan) [inline monitor/metrics/store.go]: `defer Unlock` above

**Comment by hsanjuan** [comment]
Also, mind the codeclimate warning!

File: monitor/metrics/checker.go (hunk 1 above)
Comment (hsanjuan) [reply monitor/metrics/checker.go]: actually, `map[peer.ID]int` and record how many times something has alerted, and then make the threshold of number of times something should alert at most a variable at the top?

File: monitor/metrics/store.go (hunk 3 above)
Comment (lanzafame) [reply monitor/metrics/store.go]: Overhead of defer is non-trivial, so since this doesn't have multiple returns, I preferred to leave as is.

**Comment by lanzafame** [comment]
> This means that a peer re-appearing will need to fill-in the window up to 5 for the distribution to kick in and eventually trigger alerts (which is good).

This is updated in #815.

**Comment by lanzafame** [comment]
@hsanjuan We should probably take the `-failfast` out of the travis config so that we know if just a single flaky test failed or if there were several other test failures.

**Comment by hsanjuan** [comment]
The problem is that if the AlertThreshold is set to 1 we only send 1 alert regardless of the metrics alerting. So we end up sending only a `freespace` alert and not a `freespace` and a `ping` alert.
