### PR TITLE
When a peer is removed, clear it from peerstore 

### LINKED ISSUE #840: [Raft] peers rm doesn't actually remove the peer
**Additional information:**
 - OS: Linux
 - IPFS Cluster version: 0.11.0-rc4
 - Installation method: docker

**Describe the bug:**

Running `ipfs-cluster-ctl peers rm <peerid>` logs that it removes the peer but then attempts to connect that peer again. Logs:
```
06:33:28.758  INFO  pstoremgr: connecting to QmPu66JRV1CWHXVz7XJDXdkobjrPoyecs6fA2DhiswP2to pstoremgr.go:315
06:33:33.759 WARNI  pstoremgr: context deadline exceeded pstoremgr.go:318
06:33:45.067  INFO    cluster: re-allocating all CIDs directly associated to QmPu66JRV1CWHXVz7XJDXdkobjrPoyecs6fA2DhiswP2to cluster.go:810
06:33:45.073  INFO    cluster: Peer removed  QmPu66JRV1CWHXVz7XJDXdkobjrPoyecs6fA2DhiswP2to cluster.go:818
06:33:58.758  INFO  pstoremgr: connecting to QmPu66JRV1CWHXVz7XJDXdkobjrPoyecs6fA2DhiswP2to pstoremgr.go:315
06:34:03.760 WARNI  pstoremgr: context deadline exceeded pstoremgr.go:318
```

Note this peer doesn't exist anymore, and no other peer in the cluster thinks it is still around.

Normally, removing the peerstore after shutting the peer down would be a workaround to this, but I don't have access to the volume once the peer has been shutdown.

### PR DESCRIPTION
**Pull request by kishansagathiya**
With this PR, cluster peer will observe on events of peer removal
from cluster. On occurence of the event, the cluster peer will clear
the removed peer from its peerstore.

Fixes #840

### CODE REVIEW

File: consensus/raft/raft.go [hunk 1]
```diff
@@ -686,3 +695,47 @@ func find(s []string, elem string) bool {
 	}
 	return false
 }
+
+func (rw *raftWrapper) observePeers() {
+	obsCh := make(chan hraft.Observation, 1)
+	defer close(obsCh)
+
+	if !sixtyfour {
+		// 32-bit systems don't support observers
```
Comment (kishansagathiya) [inline consensus/raft/raft.go]: I am not sure what was the issue here.

https://github.com/hashicorp/raft/blob/dcbf3052ba602706d2a0baa7c51a4f23c597dd7f/observer.go#L40-L43 makes me think that it is fixed
There is a PR with similar problem containing more details.

File: consensus/raft/raft.go [hunk 2]
```diff
@@ -686,3 +695,47 @@ func find(s []string, elem string) bool {
...
+		// TODO: Check if this is still the case?
+		logger.Warning("raft Observers panic on 32-bit architecture")
+		return
+	}
+
+	observer := hraft.NewObserver(obsCh, false, nil)
```
Comment (hsanjuan) [inline consensus/raft/raft.go]: why not blocking?

Comment (hsanjuan) [reply consensus/raft/raft.go]: and why not filtering?

File: consensus/raft/raft.go [hunk 3]
```diff
@@ -686,3 +695,47 @@ func find(s []string, elem string) bool {
...
+	defer rw.raft.DeregisterObserver(observer)
+
+	for {
+		select {
+		case obs := <-obsCh:
+			switch obs.Data.(type) {
+			case hraft.PeerObservation:
+				pObs := obs.Data.(hraft.PeerObservation)
+				if pObs.Removed {
+					logger.Infof("Observed removal of raft peer: %s",
```
Comment (hsanjuan) [inline consensus/raft/raft.go]: we have a tendency to start log messages with lowercase. (golint complains for Printlns). Message could be a bit more informative: `raft peer departed. Removing from peerstore`.

File: consensus/raft/raft.go [hunk 4]
```diff
@@ -686,3 +695,47 @@ func find(s []string, elem string) bool {
...
+					}
+					err = rw.peerManager.RmPeer(pID)
+					if err != nil {
+						logger.Error(err)
+					}
+				}
+			default:
+			}
+		case <-rw.finishObs:
+			close(rw.finishObs)
```
Comment (hsanjuan) [inline consensus/raft/raft.go]: channels should be closed by the senders, never by the receivers. But you want to use a context anyways. Have the raftWrapper keep a context that can be cancelled on shutdown.

File: consensus/raft/raft.go [hunk 5]
```diff
@@ -79,6 +82,7 @@ func newRaftWrapper(
 	raftW := &raftWrapper{}
 	raftW.config = cfg
 	raftW.host = host
+	raftW.peerManager = pstoremgr.New(context.Background(), host, "")
```
Comment (hsanjuan) [inline consensus/raft/raft.go]: unsure we need to carry this, if you just need a `host.Peerstore().ClearAddrs(pid)` inside the `observePeers()` function.

File: consensus/raft/raft.go (hunk 1 above)
Comment (hsanjuan) [reply consensus/raft/raft.go]: Do you have a raspberry Pi you can test with?

Comment (kishansagathiya) [reply consensus/raft/raft.go]: No, but I can order one

Comment (hsanjuan) [reply consensus/raft/raft.go]: I think you can just build for 32 bit architecture and run it

Comment (kishansagathiya) [reply consensus/raft/raft.go]: I think it works. 

I commented this sixtyfour check.
installed cluster like this `env GOOS=linux GOARCH=386 make install`
ran a cluster with two peers, remove one of them with `peers rm`
other peer observed it successfully and removed it from peerstore, just like 64 bit.

File: consensus/raft/raft.go (hunk 2 above)
Comment (kishansagathiya) [reply consensus/raft/raft.go]: filtering I have done after receiving observations, but I can change it to here.

Making blocking true will cause raft to block when sending observation. I dont see a strong reason to do so. Generally it should be false.
https://github.com/hashicorp/raft/blob/ff523e1c1515a5b33cc3153a34c984093fed06bb/observer.go#L50-L51

Comment (hsanjuan) [reply consensus/raft/raft.go]: > I dont see a strong reason to do so

Think again. If several peers are removed at once and Raft cannot put them in the channel, you will never get notified. Yes, there are strong reasons to block so you don't miss any observation. There are mild reasons to filter. I'm ok with no filtering.

File: consensus/raft/raft.go [hunk 6]
```diff
@@ -700,41 +698,34 @@ func (rw *raftWrapper) observePeers() {
...
 	defer close(obsCh)
 
-	if !sixtyfour {
-		// 32-bit systems don't support observers
-		// TODO: Check if this is still the case?
-		logger.Warning("raft Observers panic on 32-bit architecture")
-		return
-	}
+	observer := hraft.NewObserver(obsCh, false, func(o *hraft.Observation) bool {
+		switch o.Data.(type) {
```
Comment (hsanjuan) [inline consensus/raft/raft.go]:
```go
po,ok := o.Data.(*hraft.Observation)
return ok && po.Removed
```

File: pstoremgr/pstoremgr.go [hunk 7]
```diff
@@ -312,14 +312,14 @@ func (pm *Manager) Bootstrap(count int) []peer.ID {
 			continue
 		}
 
-		logger.Debugf("connecting to %s", pinfo.ID)
```
Comment (hsanjuan) [inline pstoremgr/pstoremgr.go]: No reason to change these and below. They were more verbose in the past and I had to tune it down because it seriously spams the logs on big clusters (and not being able to connect some peer during bootstrap is not a big deal).
