### PR TITLE
Fix #853: Make a more orderly shutdown of rest api libp2p host

### LINKED ISSUE #853: panic: emitter is closed
**Additional information:**
 - OS: Linux
 - IPFS Cluster version:  master, ef8f2cb17d03f309deb534227e565a3025a9d3cf
 - Installation method: built from source

**Describe the bug:**
 
My port for rest api was occupied, when I ran tests `go test -v ./api/rest`. Test failed as expected. I freed the port. On running the test again I saw this error

```
➜  ipfs-cluster ✗ go test -v ./api/rest 
=== RUN   TestLoadEmptyJSON
--- PASS: TestLoadEmptyJSON (0.00s)
=== RUN   TestLoadJSON
--- PASS: TestLoadJSON (0.00s)
=== RUN   TestApplyEnvVars
--- PASS: TestApplyEnvVars (0.00s)
=== RUN   TestLibp2pConfig
panic: emitter is closed

goroutine 71 [running]:
github.com/libp2p/go-eventbus.(*emitter).Emit(0xc000191200, 0xc81540, 0xc0000b7980)
	/home/kishan/code/pkg/mod/github.com/libp2p/go-eventbus@v0.0.3/basic.go:33 +0x6f
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).RemoveStreamHandler(0xc0000d62c0, 0xd4501d, 0xc)
	/home/kishan/code/pkg/mod/github.com/libp2p/go-libp2p@v0.2.1/p2p/host/basic/basic_host.go:419 +0x112
github.com/libp2p/go-libp2p-gostream.(*listener).Close(0xc000046400, 0xc00014add0, 0x10)
	/home/kishan/code/pkg/mod/github.com/libp2p/go-libp2p-gostream@v0.1.2/listener.go:39 +0x53
net/http.(*onceCloseListener).close(...)
	/usr/local/go/src/net/http/server.go:3286
sync.(*Once).Do(0xc0000b7570, 0xc00014ae00)
	/usr/local/go/src/sync/once.go:44 +0xb3
net/http.(*onceCloseListener).Close(0xc0000b7560, 0x0, 0x55)
	/usr/local/go/src/net/http/server.go:3282 +0x54
net/http.(*Server).Serve(0xc0003684e0, 0xf91f80, 0xc000046400, 0xf815e0, 0xc0000b2210)
	/usr/local/go/src/net/http/server.go:2879 +0x4b0
github.com/ipfs/ipfs-cluster/api/rest.(*API).runLibp2pServer(0xc00012b050, 0xf95700, 0xc000362980)
	/home/kishan/code/ipfs-cluster/api/rest/restapi.go:477 +0x322
created by github.com/ipfs/ipfs-cluster/api/rest.(*API).run
	/home/kishan/code/ipfs-cluster/api/rest/restapi.go:449 +0x8a
FAIL	github.com/ipfs/ipfs-cluster/api/rest	0.094s

```

Though, looking at the logs it seems like it is happening from go-eventbus

After that tests ran fine.

### PR DESCRIPTION
**Pull request by hsanjuan**
Cancelling its context before closing the listeners and de-registering
protocols is ground for panics on libp2p.

#853

### CODE REVIEW

File: api/rest/restapi.go [hunk 1]
```diff
@@ -204,6 +204,10 @@ func (api *API) setupLibp2p(ctx context.Context) error {
 	// Make new host. Override any provided existing one
```
Comment (kishansagathiya) [inline api/rest/restapi.go]:
```
func (api *API) setupLibp2p(ctx context.Context) error {
```
Why pass a context at all if not using it?

File: api/rest/restapi.go [hunk 2]
```diff
@@ -204,6 +204,10 @@ func (api *API) setupLibp2p(ctx context.Context) error {
...
 	// if we have config for a custom one.
 	if api.config.Libp2pListenAddr != nil {
+		// Use a separate host context. We will call
+		// Close() on shutdown(). Avoids things like:
+		// https://github.com/ipfs/ipfs-cluster/issues/853
+		ctx := context.Background()
```
Comment (kishansagathiya) [inline api/rest/restapi.go]: pass it directly instead of creating a var?
